# Generated by Django 5.1 on 2024-08-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mall_products', '0001_initial'),
        ('mall_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MallOrderClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Ordering Date Time')),
                ('ordering_quantity', models.IntegerField(verbose_name='Ordering Quantity')),
                ('ordering_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall_products.mallproductclass', verbose_name='Ordering Product')),
                ('ordering_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall_users.malluserclass', verbose_name='Ordering User')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
                'db_table': 'mall_order_db',
            },
        ),
    ]
